services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: comic_ecommerce
      POSTGRES_USER: comics_user
      POSTGRES_PASSWORD: comics_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
