services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: comic_ecommerce
      POSTGRES_USER: comics_user
      POSTGRES_PASSWORD: comics_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  n8n_data:
  ollama_data:        # ← agregás este también