require('dotenv').config()
const { PrismaClient } = require('@prisma/client')
const { PrismaPg } = require('@prisma/adapter-pg')
const bcrypt = require('bcryptjs')

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

const comics = [
  // ── MARVEL ──────────────────────────────────────────────────────────────
  {
    id: 1,
    title: 'The Amazing Spider-Man',
    author: 'Todd McFarlane',
    description: 'La batalla final entre Spider-Man y Venom. Primera aparición completa del simbionte en el cuerpo de Eddie Brock.',
    price: 24.99,
    stock: 15,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=SPIDER-MAN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 48,
    edition: 'Edición Especial',
    issueNumber: 'Nº 300',
  },
  {
    id: 2,
    title: "Avengers: Earth's Mightiest Heroes",
    author: 'Brian Michael Bendis',
    description: 'Los héroes más poderosos de la Tierra se reúnen para detener a Kang el Conquistador en una épica intergaláctica.',
    price: 35.00,
    stock: 10,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=AVENGERS',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 64,
    edition: 'Edición Limitada',
    issueNumber: null,
  },
  {
    id: 3,
    title: 'X-Men: Mutant Genesis',
    author: 'Jim Lee',
    description: 'El renacimiento de la patrulla mutante bajo la legendaria pluma de Jim Lee. Magneto desata su poder sobre el mundo.',
    price: 19.99,
    stock: 20,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=X-MEN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 56,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 4,
    title: 'Daredevil: La Saga',
    author: 'Frank Miller',
    description: 'Matt Murdock y Elektra fundan el Puño para destruir a la Mano en una historia de traición y redención.',
    price: 200.00,
    stock: 3,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=DAREDEVIL',
    category: 'Superhéroes',
    language: 'es',
    publisher: 'Marvel',
    pages: 120,
    edition: 'Edición Especial',
    issueNumber: null,
  },
  {
    id: 5,
    title: 'Wolverine: Old Man Logan',
    author: 'Mark Millar',
    description: 'En un futuro distópico donde los villanos ganaron, Logan recorre una América post-apocalíptica para salvar a su familia.',
    price: 29.99,
    stock: 8,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=WOLVERINE',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 240,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 6,
    title: 'Thor: God of Thunder Vol. 1',
    author: 'Jason Aaron',
    description: 'Un dios asesino de dioses acecha el universo a través del tiempo. Thor en tres épocas distintas enfrenta a Gorr.',
    price: 22.50,
    stock: 12,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=THOR',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 136,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 7,
    title: 'Iron Man: Extremis',
    author: 'Warren Ellis',
    description: 'Tony Stark se enfrenta a la tecnología Extremis, un nanosuero que redefine los límites de lo humano y lo mecánico.',
    price: 18.99,
    stock: 18,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=IRON-MAN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 144,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 8,
    title: 'Captain America: The Winter Soldier',
    author: 'Ed Brubaker',
    description: 'Steve Rogers descubre que Bucky Barnes, su compañero caído, fue convertido en un arma letal por los soviéticos.',
    price: 27.99,
    stock: 11,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=CAP-AMERICA',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 176,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 9,
    title: 'Guardians of the Galaxy Vol. 1',
    author: 'Brian Michael Bendis',
    description: 'Una pandilla de inadaptados cósmicos protege la galaxia. Star-Lord lidera al equipo más disfuncional del universo.',
    price: 16.99,
    stock: 22,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=GOTG',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Marvel',
    pages: 136,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 10,
    title: 'Black Panther: A Nation Under Our Feet',
    author: 'Ta-Nehisi Coates',
    description: "T'Challa enfrenta una revolución en Wakanda mientras cuestiona su rol como rey en una nación que lo desafía.",
    price: 24.99,
    stock: 9,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=BLACK-PANTHER',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 160,
    edition: 'Tapa Dura',
    issueNumber: 'Vol. 1',
  },
  {
    id: 11,
    title: 'Doctor Strange: The Oath',
    author: 'Brian K. Vaughan',
    description: 'El Hechicero Supremo investiga un atentado contra su propia vida mientras busca una cura para una enfermedad mortal.',
    price: 19.99,
    stock: 14,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=DR-STRANGE',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 128,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 12,
    title: 'Punisher MAX Vol. 1',
    author: 'Garth Ennis',
    description: 'Frank Castle regresa con la versión más oscura y brutal del Castigador. Sin código de colores. Solo violencia.',
    price: 17.99,
    stock: 7,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=PUNISHER',
    category: 'Policial',
    language: 'en',
    publisher: 'Marvel',
    pages: 144,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 13,
    title: 'Ms. Marvel Vol. 1: No Normal',
    author: 'G. Willow Wilson',
    description: 'Kamala Khan descubre sus poderes polimórficos y debe equilibrar su identidad entre dos mundos.',
    price: 15.99,
    stock: 25,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=MS-MARVEL',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 120,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 14,
    title: 'Moon Knight: From the Dead',
    author: 'Warren Ellis',
    description: 'Marc Spector enfrenta amenazas sobrenaturales mientras su psique fragmentada cuestiona la realidad misma.',
    price: 21.99,
    stock: 6,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=MOON-KNIGHT',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 136,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 15,
    title: 'Deadpool: Kills the Marvel Universe',
    author: 'Cullen Bunn',
    description: 'Wade Wilson pierde la razón y decide eliminar a todos los héroes y villanos del universo Marvel. Sin excepciones.',
    price: 14.99,
    stock: 30,
    imageUrl: 'https://placehold.co/300x450/ED1D24/FFFFFF?text=DEADPOOL',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Marvel',
    pages: 112,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  // ── DC ──────────────────────────────────────────────────────────────────
  {
    id: 16,
    title: 'Batman: Year One',
    author: 'Frank Miller',
    description: 'El origen del Caballero Oscuro por Frank Miller. Bruce Wayne vuelve a Gotham y comienza su cruzada solitaria.',
    price: 22.50,
    stock: 5,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=BATMAN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 96,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 17,
    title: 'Lobo: Último Czarniano',
    author: 'Alan Grant',
    description: 'El bounty hunter más peligroso del universo DC. Violencia, humor negro y caos cósmico en cada página.',
    price: 180.00,
    stock: 4,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=LOBO',
    category: 'Superhéroes',
    language: 'es',
    publisher: 'DC',
    pages: 64,
    edition: 'Edición Normal',
    issueNumber: null,
  },
  {
    id: 18,
    title: 'The Dark Knight Returns',
    author: 'Frank Miller',
    description: 'Un Batman envejecido vuelve de su retiro para limpiar Gotham una última vez. Obra cumbre del cómic moderno.',
    price: 24.99,
    stock: 8,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=DARK-KNIGHT',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 224,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 19,
    title: 'Watchmen',
    author: 'Alan Moore',
    description: 'Superhéroes retirados son asesinados uno a uno. Una deconstrucción total del género que redefinió el cómic.',
    price: 39.99,
    stock: 12,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=WATCHMEN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 416,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 20,
    title: 'Superman: Red Son',
    author: 'Mark Millar',
    description: '¿Qué hubiera pasado si la cápsula de Kal-El hubiera caído en la URSS? Un elseworlds definitivo.',
    price: 17.99,
    stock: 16,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=SUPERMAN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 160,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 21,
    title: 'Green Lantern: Secret Origin',
    author: 'Geoff Johns',
    description: 'Hal Jordan descubre el anillo del Cuerpo de Linternas Verdes y se convierte en el mayor lanterna de la galaxia.',
    price: 19.99,
    stock: 13,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=GREEN-LANTERN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 168,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 22,
    title: 'Sandman Vol. 1: Preludes & Nocturnes',
    author: 'Neil Gaiman',
    description: 'Morfeo, el Rey de los Sueños, escapa de una prisión mágica y parte en busca de sus artefactos robados.',
    price: 29.99,
    stock: 7,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=SANDMAN',
    category: 'Fantasía',
    language: 'en',
    publisher: 'DC',
    pages: 240,
    edition: 'Tapa Dura',
    issueNumber: 'Vol. 1',
  },
  {
    id: 23,
    title: 'V for Vendetta',
    author: 'Alan Moore',
    description: 'En una Inglaterra fascista, un misterioso enmascarado lleva a cabo una campaña de caos contra el régimen totalitario.',
    price: 19.99,
    stock: 20,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=V-VENDETTA',
    category: 'Policial',
    language: 'en',
    publisher: 'DC',
    pages: 296,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 24,
    title: 'Swamp Thing: Saga of the Swamp Thing',
    author: 'Alan Moore',
    description: 'Alan Moore redefine a Swamp Thing: no es un humano convertido en planta, sino la planta que cree ser humano.',
    price: 24.99,
    stock: 6,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=SWAMP-THING',
    category: 'Horror',
    language: 'en',
    publisher: 'DC',
    pages: 208,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 25,
    title: 'Justice League: Origin',
    author: 'Geoff Johns',
    description: 'El primer encuentro entre Batman, Superman, Wonder Woman y los demás en el universo New 52 de DC.',
    price: 22.99,
    stock: 18,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=JUSTICE-LEAGUE',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 192,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 26,
    title: 'The Flash: Rebirth',
    author: 'Geoff Johns',
    description: 'Barry Allen regresa de entre los muertos y debe enfrentar la amenaza de Zoom mientras recupera su lugar como Flash.',
    price: 17.99,
    stock: 14,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=THE-FLASH',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 168,
    edition: 'Tapa Blanda',
    issueNumber: null,
  },
  {
    id: 27,
    title: 'Wonder Woman Vol. 1: Blood',
    author: 'Brian Azzarello',
    description: 'Diana descubre que su origen es una mentira y debe proteger a una mortal embarazada de los dioses del Olimpo.',
    price: 19.99,
    stock: 11,
    imageUrl: 'https://placehold.co/300x450/1A1A2E/FFFFFF?text=WONDER-WOMAN',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'DC',
    pages: 208,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  // ── IMAGE COMICS ────────────────────────────────────────────────────────
  {
    id: 28,
    title: 'Saga Vol. 1',
    author: 'Brian K. Vaughan',
    description: 'Una pareja de razas enemigas huye con su bebé recién nacido a través de una galaxia en guerra. Épica espacial adulta.',
    price: 9.99,
    stock: 35,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=SAGA',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Image',
    pages: 160,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 29,
    title: 'The Walking Dead Vol. 1: Days Gone Bye',
    author: 'Robert Kirkman',
    description: 'Rick Grimes despierta de un coma en un mundo invadido por zombis. El comienzo de la saga más larga del cómic indie.',
    price: 14.99,
    stock: 28,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=WALKING-DEAD',
    category: 'Horror',
    language: 'en',
    publisher: 'Image',
    pages: 144,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 30,
    title: 'Invincible Vol. 1: Family Matters',
    author: 'Robert Kirkman',
    description: 'Mark Grayson hereda los poderes de su padre pero pronto descubre que ser superhéroe tiene un costo devastador.',
    price: 12.99,
    stock: 20,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=INVINCIBLE',
    category: 'Superhéroes',
    language: 'en',
    publisher: 'Image',
    pages: 128,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 31,
    title: 'Spawn Origins Vol. 1',
    author: 'Todd McFarlane',
    description: 'Al Simmons, un agente de la CIA asesinado, vuelve del infierno convertido en un soldado infernal con poderes oscuros.',
    price: 14.99,
    stock: 10,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=SPAWN',
    category: 'Horror',
    language: 'en',
    publisher: 'Image',
    pages: 176,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 32,
    title: 'East of West Vol. 1',
    author: 'Jonathan Hickman',
    description: 'En un Estados Unidos alternativo dividido en naciones, los Cuatro Jinetes del Apocalipsis desatan el fin del mundo.',
    price: 9.99,
    stock: 17,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=EAST-OF-WEST',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Image',
    pages: 160,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 33,
    title: 'Lazarus Vol. 1',
    author: 'Greg Rucka',
    description: 'En un futuro corporativo, Forever Carlyle es el arma biológica de su familia. Una historia de lealtad y dudas.',
    price: 9.99,
    stock: 15,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=LAZARUS',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Image',
    pages: 136,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 34,
    title: 'Monstress Vol. 1: Awakening',
    author: 'Marjorie Liu',
    description: 'En un mundo matriarcal de magia y guerra, Maika lleva dentro un monstruo antiguo que despertó hambriento.',
    price: 16.99,
    stock: 9,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=MONSTRESS',
    category: 'Fantasía',
    language: 'en',
    publisher: 'Image',
    pages: 192,
    edition: 'Tapa Dura',
    issueNumber: 'Vol. 1',
  },
  {
    id: 35,
    title: 'Paper Girls Vol. 1',
    author: 'Brian K. Vaughan',
    description: 'Cuatro repartidoras de periódicos de los 80 quedan atrapadas en una guerra temporal que amenaza toda la existencia.',
    price: 9.99,
    stock: 23,
    imageUrl: 'https://placehold.co/300x450/F7941D/FFFFFF?text=PAPER-GIRLS',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Image',
    pages: 144,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  // ── DARK HORSE ──────────────────────────────────────────────────────────
  {
    id: 36,
    title: 'Sin City Vol. 1: The Hard Goodbye',
    author: 'Frank Miller',
    description: 'Marv, un matón con corazón de oro, sale a vengar la muerte de la única persona que lo amó. Noir en estado puro.',
    price: 19.00,
    stock: 11,
    imageUrl: 'https://placehold.co/300x450/2B2B2B/FFFFFF?text=SIN-CITY',
    category: 'Policial',
    language: 'en',
    publisher: 'Dark Horse',
    pages: 208,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 37,
    title: 'Hellboy Vol. 1: Seed of Destruction',
    author: 'Mike Mignola',
    description: 'Hellboy investiga la resurrección de un antiguo dios lovecraftiano mientras descubre la verdad sobre su origen.',
    price: 17.99,
    stock: 14,
    imageUrl: 'https://placehold.co/300x450/2B2B2B/FFFFFF?text=HELLBOY',
    category: 'Horror',
    language: 'en',
    publisher: 'Dark Horse',
    pages: 128,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 38,
    title: 'BPRD Vol. 1: Hollow Earth',
    author: 'Mike Mignola',
    description: 'El equipo de Defensa y Paranormalidad enfrenta una amenaza subterránea mientras Hellboy está fuera de combate.',
    price: 17.99,
    stock: 8,
    imageUrl: 'https://placehold.co/300x450/2B2B2B/FFFFFF?text=BPRD',
    category: 'Horror',
    language: 'en',
    publisher: 'Dark Horse',
    pages: 144,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
  {
    id: 39,
    title: 'Star Wars: Dark Empire',
    author: 'Tom Veitch',
    description: 'El Emperador renace en un cuerpo clónico y Luke Skywalker cae al Lado Oscuro. Secuela canónica de Return of the Jedi.',
    price: 24.99,
    stock: 6,
    imageUrl: 'https://placehold.co/300x450/2B2B2B/FFFFFF?text=STAR-WARS',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Dark Horse',
    pages: 184,
    edition: 'Tapa Dura',
    issueNumber: null,
  },
  {
    id: 40,
    title: 'Aliens Vol. 1',
    author: 'Mark Verheiden',
    description: 'Hicks y Newt, supervivientes de LV-426, enfrentan una invasión Xenomorph en la Tierra. Terror sci-fi en su máxima expresión.',
    price: 16.99,
    stock: 10,
    imageUrl: 'https://placehold.co/300x450/2B2B2B/FFFFFF?text=ALIENS',
    category: 'Ciencia Ficción',
    language: 'en',
    publisher: 'Dark Horse',
    pages: 128,
    edition: 'Tapa Blanda',
    issueNumber: 'Vol. 1',
  },
]

async function main() {
  const adminEmail = 'admin@comicscorp.local'
  const adminPassword = 'Admin123!'
  const hashedAdminPassword = await bcrypt.hash(adminPassword, 10)

  console.log('Seeding admin user...')
  await prisma.user.upsert({
    where: { email: adminEmail },
    update: {
      name: 'Admin Comics Corp',
      password: hashedAdminPassword,
      role: 'ADMIN',
    },
    create: {
      email: adminEmail,
      password: hashedAdminPassword,
      name: 'Admin Comics Corp',
      role: 'ADMIN',
    },
  })
  console.log(`Admin user ready: ${adminEmail} / ${adminPassword}`)

  console.log('Seeding comics...')
  for (const comic of comics) {
    const { id, ...comicData } = comic

    await prisma.comic.upsert({
      where: { id },
      update: comicData,
      create: comicData,
    })
  }
  await prisma.$executeRawUnsafe(
    `SELECT setval(pg_get_serial_sequence('"Comic"', 'id'), COALESCE((SELECT MAX(id) FROM "Comic"), 1))`
  )
  console.log(`✓ ${comics.length} comics seeded successfully`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
